files: |-
  (?x)
  ^(?:
       (src/.*)
      |(tests/.*)
      |(examples/.*)
      |(docs/examples/.*)
      |(docs/custom_ext/.*)
      |(benchmarks/.*)
      |(scripts/.*)
      |(.github/.*)
      |(.pre-commit-config.yaml)
  )$

default_stages:
  - pre-commit
  - pre-push

repos:
  - repo: 'https://github.com/pre-commit/pre-commit-hooks'
    rev: v5.0.0
    hooks:
      - id: check-merge-conflict
      - id: debug-statements
        exclude: ^.*_312\.py$
      - id: detect-private-key
      - id: trailing-whitespace
      - id: check-added-large-files
        args: ['--maxkb=100']

  - repo: 'https://github.com/myint/eradicate'
    rev: 2.3.0
    hooks:
      - id: eradicate
        args: ['-e']  # remove default --in-place argument and emit error

  - repo: 'https://github.com/astral-sh/ruff-pre-commit'
    rev: v0.9.1
    hooks:
      - id: ruff
        args: [ --fix-only ]

  - repo: 'https://github.com/pycqa/isort'
    rev: 5.13.2
    hooks:
      - id: isort

  - repo: 'https://github.com/python-jsonschema/check-jsonschema'
    rev: 0.31.0
    hooks:
      - id: check-dependabot
      - id: check-github-workflows

  - repo: 'https://github.com/rhysd/actionlint'
    rev: v1.7.3
    hooks:
      - id: actionlint

  - repo: 'https://github.com/woodruffw/zizmor-pre-commit'
    rev: v1.1.1
    hooks:
      - id: zizmor

  - repo: meta
    hooks:
      - id: check-hooks-apply
      - id: check-useless-excludes
