name: Run linters and tests

on:
  push:
    branches-ignore:
      - "2.x/*"
  pull_request:
    branches-ignore:
      - "2.x/*"
  workflow_dispatch:

permissions:
  contents: read

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  linting:
    name: Linting
    runs-on: ubuntu-latest
    timeout-minutes: 3

    steps:
      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683
        with:
          persist-credentials: false

      - name: Set up Python 3.11
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install Just
        uses: extractions/setup-just@dd310ad5a97d8e7b41793f8ef055398d51ad4de6
        with:
          just-version: 1.14.0

      - name: Setup environment to run tox
        env:
          UV_SYSTEM_PYTHON: 1
        run:
          just setup-runner

      - name: Run linters
        run:
          just lint

  testing:
    name: Testing (${{ matrix.python_version.tox }}, ${{ matrix.os }})
    runs-on: ${{ matrix.os }}
    needs: linting

    strategy:
      fail-fast: true
      matrix:
        python_version:
          - { setup: '3.9',      tox: 'py39',    cov: true  }
          - { setup: '3.10',     tox: 'py310',   cov: true  }
          - { setup: '3.11',     tox: 'py311',   cov: true  }
          - { setup: '3.12.3',   tox: 'py312',   cov: true  }  # (1)
          - { setup: '3.13',     tox: 'py313',   cov: true  }
          - { setup: 'pypy3.9',  tox: 'pypy39',  cov: false }
          - { setup: 'pypy3.10', tox: 'pypy310', cov: false }

        # (1): 3.12.4 contains backwards-incompatible changes of ForwardRef._evaluate()
        os: ['ubuntu-latest']

    steps:
      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683
        with:
          persist-credentials: false

      - name: Set up Python 3.11
        uses: actions/setup-python@f677139bbe7f9c59b41e40162b753c062f5d49a3
        with:
          python-version: ${{ matrix.python_version.setup }}

      - name: Install Just
        uses: extractions/setup-just@dd310ad5a97d8e7b41793f8ef055398d51ad4de6
        with:
          just-version: 1.14.0

      - name: Setup environment to run tox
        env:
          UV_SYSTEM_PYTHON: 1
        run:
          just setup-runner

      - name: Run tests with coverage
        if: ${{  (matrix.python_version.cov && github.event_name == 'pull_request') }}
        run:
          just inv test-on-ci
            --py-target ${{ matrix.python_version.tox }}
            --cov-output .coverage.${{ matrix.python_version.tox }}

      - name: Store coverage file
        uses: actions/upload-artifact@4cec3d8aa04e39d1a68397de0c4cd6fb9dce8ec1
        if: ${{  (matrix.python_version.cov && github.event_name == 'pull_request') }}
        with:
          name: coverage-${{ matrix.python_version.tox }}
          path: .coverage.${{ matrix.python_version.tox }}
          if-no-files-found: error
          include-hidden-files: true

      - name: Run tests without coverage
        if: ${{ !(matrix.python_version.cov && github.event_name == 'pull_request') }}
        run:
          just inv test-on-ci
            --py-target ${{ matrix.python_version.tox }}

  coverage:
    name: Coverage
    runs-on: ubuntu-latest
    needs: testing
    permissions:
      pull-requests: write

    if: ${{ github.event_name == 'pull_request' }}

    steps:
      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683
        with:
          persist-credentials: false

      - uses: actions/download-artifact@fa0a91b85d4f404e444e00e005971372dc801d16
        id: download
        with:
          pattern: coverage-*
          merge-multiple: true

      - name: Coverage comment
        id: coverage_comment
        uses: py-cov-action/python-coverage-comment-action@b2eb38dd175bf053189b35f738f9207278b00925
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          MERGE_COVERAGE_FILES: true
          MINIMUM_GREEN: 90

      - name: Store Pull Request comment to be posted (for external pr)
        uses: actions/upload-artifact@4cec3d8aa04e39d1a68397de0c4cd6fb9dce8ec1
        if: steps.coverage_comment.outputs.COMMENT_FILE_WRITTEN == 'true'
        with:
          name: python-coverage-comment-action
          path: python-coverage-comment-action.txt
